server:
  port: ${port:6060}

gateway:
  filter:
    gloabl-request-rate-count: 10
    verify-token: false

spring:
  application:
    name: gatewayService
  profiles:
    active: ${activeProfile:dev}

  config:
    import:
      - nacos:dev-common.yml
      - nacos:dev-nacos-common.yml
      - nacos:dev-log-common.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:${NACOS_PORT:8848}
        namespace: demo
        group: demo
    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true
      routes:
        - id: order
          uri: http://localhost:6061
          predicates:
            - Path=/order/**
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: '#{@myKeyResolver}'
                redis-rate-limiter.replenishRate: 1 # 每秒生产多少个令牌
                redis-rate-limiter.burstCapacity: 0 # 令牌桶容量
        #
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/
        # The requested URL /dataService4/data/check/105 was not found on this server.
        - id: data
          uri: http://www.baidu.com
          # 必须小于0，routes配置才会覆盖discovery.locator里的配置
          order: -1
          predicates:
              - Path=/dataService4/data/check/**
  redis:
    host: 192.168.5.25
    port: 6381
    password: Ld123!@#

logging:
  level:
    org.springframework.cloud.gateway: debug