server:
  port: ${port:6061}

management:
  security:
    enabled: true
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: orderService4
  profiles:
    active: ${activeProfile:dev}
  security:
    user:
      name: admin
      password: 123456
  cloud:
    nacos:
      config:
        server-addr: @nacos.addr@:${NACOS_PORT:8848}
        namespace: demo
        group: demo
  config:
    import:
      - nacos:@profiles.active@-common.yml
      - nacos:@profiles.active@-order.yml
      - nacos:@profiles.active@-nacos-common.yml
      - nacos:@profiles.active@-mysql-common.yml