db:
  num: 1
  user: ${MYSQL_USER:lvdong}
  password: ${MYSQL_PWD:Ld123!@#}
  url:
    0: jdbc:mysql://${MYSQL_HOST:dev-mysql-01.db.cloud.lvdong.com}:${MYSQL_PORT:3306}/${MYSQL_DB:ld_config}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
